# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - run: |
          cd md2pdf
          sudo apt-get install -y python3-setuptools
          sudo pip3 install -r requirements.txt
          sudo python3 setup.py install
          cd ..
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb ~
          sudo dpkg -i ~/wkhtmltox_0.12.6-1.focal_amd64.deb
          python3 -m md2pdf -c github.css README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
      # Required
          commit_message: Generate CV PDF

      # Optional local file path to the repository
          repository: .

      # Optional commit user and author settings
          commit_user_name: Eric
          commit_user_email: git@moynihan.io
